// Regenerate src/linkMasks.js from the tracer's link_masks.json.
//   node make_link_masks.mjs
// link_masks.json is what mask_tool.html saves; src/linkMasks.js is what the
// app imports. Run this after every tracing session so the two cannot drift,
// then rerun eval_masks.mjs to score the result before committing.
import { readFileSync, writeFileSync } from "fs";

const masks = JSON.parse(readFileSync("./link_masks.json", "utf8"));
const header = `// Decision regions for the photo scanner, one per link: the printed route the
// link tile sits on, traced as a polyline on the board render with a band
// width, in the same normalized 0-1 canonical coordinates as linkPositions.js.
//
// These replace the fixed radius-60 disc around each sample point. A disc
// centred on a point reaches into whichever neighbouring route happens to pass
// nearby, which is what made the crowded links around Birmingham ambiguous; a
// band that follows one route excludes the others by construction. On the four
// ground-truth games this moved 145/156 auto-correct with 11 review to 152/156
// with 4, still with no wrong automatic answers.
//
// Generated by scripts/reference-tools/make_link_masks.mjs from link_masks.json,
// which scripts/reference-tools/mask_tool.html writes. Width is in canonical
// px; 60 is the plateau of the width sweep, and past ~90 the bands start to
// swallow their neighbours again. A link with no entry here falls back to the
// disc.
export const LINK_MASKS = {
`;
const body = Object.keys(masks).sort().map((id) => {
  const { pts, width } = masks[id];
  return `  "${id}": { pts: [${pts.map((p) => `[${p[0]}, ${p[1]}]`).join(", ")}], width: ${width} },`;
}).join("\n");

writeFileSync("../../src/linkMasks.js", header + body + "\n};\n");
console.log(`written src/linkMasks.js (${Object.keys(masks).length} links)`);
